name: 'CI'

on:
    - 'push'
    - 'pull_request'
env:
    IS_GITHUB: 'true'
    XDEBUG_MODE: 'coverage'
    COMPOSER_AUTH: '{"github-oauth": {"github.com": "${{ secrets.APP_GITHUB_TOKEN }}" }}'

jobs:
    phpunit:
        runs-on: 'ubuntu-latest'

        strategy:
            fail-fast: false
            matrix:
                php_version:
                    - '8.1.18'
                    - '8.2.5'

        steps:
            -
                uses: 'actions/checkout@v3'
            -
                name: 'Redis - 6379'
                uses: 'supercharge/redis-github-action@1.5.0'
                with:
                    redis-container-name: 'redis_url1'
                    redis-port: 6379
            -
                name: 'Redis - 6380'
                uses: 'supercharge/redis-github-action@1.5.0'
                with:
                    redis-container-name: 'redis_url2'
                    redis-port: 6380
            -
                name: 'Redis - 7000-7005 cluster'
                uses: 'vishnudxb/redis-cluster@1.0.5'
                with:
                    master1-port: 7000
                    master2-port: 7001
                    master3-port: 7002
                    slave1-port: 7003
                    slave2-port: 7004
                    slave3-port: 7005
            -
                name: 'Install PHP Packages'
                uses: 'php-actions/composer@v6'
                with:
                    version: '2.x'
                    php_version: '${{ matrix.php_version }}'
                    php_extensions: >-
                        redis
                        pcov
            -
                name: 'Lint - phpcs'
                uses: 'php-actions/composer@v6'
                with:
                    version: '2.x'
                    php_version: '${{ matrix.php_version }}'
                    php_extensions: >-
                        redis
                        pcov
                    command: 'run'
                    args: 'lint:phpcs'
            -
                name: 'Test - All'
                uses: 'php-actions/composer@v6'
                continue-on-error: true
                with:
                    version: '2.x'
                    php_version: '${{ matrix.php_version }}'
                    php_extensions: >-
                        redis
                        pcov
                    command: 'run'
                    args: 'test:all'
